apiVersion: v1
appVersion: "1.1"
description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge via INWX
name: cert-manager-webhook-inwx
version: 1.2.1
home: https://github.com/rubenv/cert-manager-webhook-inwx
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
keywords:
  - cert-manager
  - webhook
  - letsencrypt
  - INWX
  - ACME
  - DNS01
maintainers:
  - name: Flying Lama
    url: https://github.com/rubenv/cert-manager-webhook-inwx
